import sys
from PyQt6 import QtWidgets, uic
from PyQt6.QtWidgets import QTableWidgetItem, QMessageBox
from model import NewtonRaphsonModel


class NewtonController(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()

        # 1. Load the View (The .ui file generated by Qt Designer)
        try:
            uic.loadUi('view.ui', self)
        except FileNotFoundError:
            print("Error: view.ui not found. Please ensure it is in the same directory.")
            sys.exit(1)

        # 2. Initialize the Model
        self.model = NewtonRaphsonModel()

        # 3. Connect UI signals to Controller slots
        self.btnSolve.clicked.connect(self.calculate)

        # Setup Table Header stretching
        header = self.tableIterations.horizontalHeader()
        header.setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)

    def calculate(self):
        """Handles the Solve button click."""

        # A. Get Inputs from View
        func_str = self.inputFunction.text()
        guess_str = self.inputGuess.text()
        tol_str = self.inputTol.text()

        # B. Basic Input Validation
        if not func_str or not guess_str:
            self.show_error("Please enter both a function and an initial guess.")
            return

        try:
            guess = float(guess_str)
            tol = float(tol_str)
        except ValueError:
            self.show_error("Initial guess and Tolerance must be numbers.")
            return

        # C. Call the Model
        result = self.model.solve(func_str, guess, tol)

        # D. Update the View based on results
        if 'error' in result:
            self.show_error(f"Math Error: {result['error']}")
            return

        # Update Result Label
        if result['root'] is not None:
            self.lblResult.setText(f"Root: {result['root']:.6f}")
            self.lblResult.setStyleSheet("color: green; font-size: 14pt; font-weight: bold;")
        else:
            self.lblResult.setText(result['message'])
            self.lblResult.setStyleSheet("color: red; font-size: 12pt;")

        # Populate the Table
        self.populate_table(result['history'])

    def populate_table(self, history):
        """Fills the QTableWidget with iteration data."""
        self.tableIterations.setRowCount(0)  # Clear previous

        for row_idx, data in enumerate(history):
            self.tableIterations.insertRow(row_idx)

            # Format data to 6 decimal places
            items = [
                str(data['iteration']),
                f"{data['x_n']:.6f}",
                f"{data['f_x']:.6f}",
                f"{data['df_x']:.6f}"
            ]

            for col_idx, val in enumerate(items):
                item = QTableWidgetItem(val)
                self.tableIterations.setItem(row_idx, col_idx, item)

    def show_error(self, message):
        QMessageBox.critical(self, "Error", message)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = NewtonController()
    window.show()
    sys.exit(app.exec())